/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import defaults.*;
import java.io.File;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDialog;
import javax.swing.JFileChooser;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author Giorgio
 */
public class GuiMain extends javax.swing.JFrame {

    /**
     * Creates new form GuiMain
     */
    
    
    String filenameOpen,filenameSave;
    MainClass main;
    CoupleDialogAdd addCouples;
    public GuiMain() {
        initComponents();
        main=new MainClass();
        main.loadXml("src/defaults/Coppia.xml");
        //addCouples=new CoupleDialogAdd(main.getCoppie());
        panelNotStarted.setVisible(true);
        idCouple.setText(String .valueOf(main.getCoppie().size()));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addCoupleDialog = new javax.swing.JDialog();
        namePlayer1 = new javax.swing.JTextField();
        namePlayer2 = new javax.swing.JTextField();
        idCouple = new javax.swing.JLabel();
        mobile = new javax.swing.JComboBox();
        addCouple = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        stopAdd = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        listCoppie = new javax.swing.JDialog();
        layers = new javax.swing.JLayeredPane();
        panelNotStarted = new javax.swing.JPanel();
        addCoppieButtonLoaded = new javax.swing.JButton();
        showCouplesLoaded = new javax.swing.JButton();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        openMenuItem = new javax.swing.JMenuItem();
        saveMenuItem = new javax.swing.JMenuItem();
        saveAsMenuItem = new javax.swing.JMenuItem();
        exitMenuItem = new javax.swing.JMenuItem();
        editMenu = new javax.swing.JMenu();
        cutMenuItem = new javax.swing.JMenuItem();
        copyMenuItem = new javax.swing.JMenuItem();
        pasteMenuItem = new javax.swing.JMenuItem();
        deleteMenuItem = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        contentsMenuItem = new javax.swing.JMenuItem();
        aboutMenuItem = new javax.swing.JMenuItem();

        addCoupleDialog.setAlwaysOnTop(true);
        addCoupleDialog.setBounds(new java.awt.Rectangle(400, 100, 300, 250));
        addCoupleDialog.setResizable(false);

        idCouple.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        idCouple.setText("1");
        idCouple.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                idCouplePropertyChange(evt);
            }
        });

        mobile.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Fissa", "Mobile" }));
        mobile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mobileActionPerformed(evt);
            }
        });

        addCouple.setText("Inserisci");
        addCouple.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCoupleActionPerformed(evt);
            }
        });

        jLabel2.setText("Nome 1");

        jLabel3.setText("Nome 2");

        stopAdd.setText("Termina");
        stopAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stopAddActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Inserimento Coppia");

        javax.swing.GroupLayout addCoupleDialogLayout = new javax.swing.GroupLayout(addCoupleDialog.getContentPane());
        addCoupleDialog.getContentPane().setLayout(addCoupleDialogLayout);
        addCoupleDialogLayout.setHorizontalGroup(
            addCoupleDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addCoupleDialogLayout.createSequentialGroup()
                .addGroup(addCoupleDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addCoupleDialogLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(mobile, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                        .addComponent(stopAdd)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(addCouple)
                        .addGap(10, 10, 10))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addCoupleDialogLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(addCoupleDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(addCoupleDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(namePlayer2, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)
                            .addComponent(namePlayer1)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addCoupleDialogLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(idCouple)
                        .addGap(59, 59, 59)))
                .addContainerGap())
        );
        addCoupleDialogLayout.setVerticalGroup(
            addCoupleDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addCoupleDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(addCoupleDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idCouple, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(addCoupleDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(namePlayer1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(addCoupleDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(namePlayer2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(29, 29, 29)
                .addGroup(addCoupleDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mobile, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addCouple)
                    .addComponent(stopAdd)))
        );

        javax.swing.GroupLayout listCoppieLayout = new javax.swing.GroupLayout(listCoppie.getContentPane());
        listCoppie.getContentPane().setLayout(listCoppieLayout);
        listCoppieLayout.setHorizontalGroup(
            listCoppieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        listCoppieLayout.setVerticalGroup(
            listCoppieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        addCoppieButtonLoaded.setText("Aggiungi Coppie");
        addCoppieButtonLoaded.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCoppieButtonLoadedActionPerformed(evt);
            }
        });

        showCouplesLoaded.setText("Elenca Coppie\\\\ngià Iscritte");
        showCouplesLoaded.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showCouplesLoadedActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelNotStartedLayout = new javax.swing.GroupLayout(panelNotStarted);
        panelNotStarted.setLayout(panelNotStartedLayout);
        panelNotStartedLayout.setHorizontalGroup(
            panelNotStartedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelNotStartedLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(showCouplesLoaded, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 81, Short.MAX_VALUE)
                .addComponent(addCoppieButtonLoaded, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelNotStartedLayout.setVerticalGroup(
            panelNotStartedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelNotStartedLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelNotStartedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(showCouplesLoaded, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addCoppieButtonLoaded, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        addCoppieButtonLoaded.getAccessibleContext().setAccessibleDescription("");

        javax.swing.GroupLayout layersLayout = new javax.swing.GroupLayout(layers);
        layers.setLayout(layersLayout);
        layersLayout.setHorizontalGroup(
            layersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layersLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(panelNotStarted, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );
        layersLayout.setVerticalGroup(
            layersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layersLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelNotStarted, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layers.setLayer(panelNotStarted, javax.swing.JLayeredPane.DEFAULT_LAYER);

        getContentPane().add(layers);

        fileMenu.setMnemonic('f');
        fileMenu.setText("File");

        openMenuItem.setMnemonic('o');
        openMenuItem.setText("Open");
        openMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(openMenuItem);

        saveMenuItem.setMnemonic('s');
        saveMenuItem.setText("Save");
        saveMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(saveMenuItem);

        saveAsMenuItem.setMnemonic('a');
        saveAsMenuItem.setText("Save As ...");
        saveAsMenuItem.setDisplayedMnemonicIndex(5);
        fileMenu.add(saveAsMenuItem);

        exitMenuItem.setMnemonic('x');
        exitMenuItem.setText("Exit");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(exitMenuItem);

        menuBar.add(fileMenu);

        editMenu.setMnemonic('e');
        editMenu.setText("Edit");

        cutMenuItem.setMnemonic('t');
        cutMenuItem.setText("Cut");
        editMenu.add(cutMenuItem);

        copyMenuItem.setMnemonic('y');
        copyMenuItem.setText("Copy");
        editMenu.add(copyMenuItem);

        pasteMenuItem.setMnemonic('p');
        pasteMenuItem.setText("Paste");
        editMenu.add(pasteMenuItem);

        deleteMenuItem.setMnemonic('d');
        deleteMenuItem.setText("Delete");
        editMenu.add(deleteMenuItem);

        menuBar.add(editMenu);

        helpMenu.setMnemonic('h');
        helpMenu.setText("Help");

        contentsMenuItem.setMnemonic('c');
        contentsMenuItem.setText("Contents");
        helpMenu.add(contentsMenuItem);

        aboutMenuItem.setMnemonic('a');
        aboutMenuItem.setText("About");
        helpMenu.add(aboutMenuItem);

        menuBar.add(helpMenu);

        setJMenuBar(menuBar);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitMenuItemActionPerformed

    private void saveMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveMenuItemActionPerformed
            final JFileChooser fc = new JFileChooser();            // TODO add your handling code here:
            fc.showDialog(panelNotStarted, null);
            File file=fc.getSelectedFile();
            filenameSave=file.getAbsolutePath();   
            
            
    }//GEN-LAST:event_saveMenuItemActionPerformed

    private void openMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openMenuItemActionPerformed
            final JFileChooser fc = new JFileChooser("D:\\dev\\JAVA\\BurracoTournament\\src\\defaults");            // TODO add your handling code here:
            fc.showDialog(panelNotStarted, null);
            File file=fc.getSelectedFile();
            filenameOpen=file.getAbsolutePath();
            main.loadXml(filenameOpen);
            idCouple.setText(String.valueOf((main.getCoppie().size())+1));
            panelNotStarted.setVisible(true);
            
    }//GEN-LAST:event_openMenuItemActionPerformed

    private void addCoppieButtonLoadedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCoppieButtonLoadedActionPerformed
               //addCoupleDialog.setVisible(true);
               addCouples=new CoupleDialogAdd(main.getCoppie());
               addCouples.setVisible(true);
    }//GEN-LAST:event_addCoppieButtonLoadedActionPerformed

    private void showCouplesLoadedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showCouplesLoadedActionPerformed
                CoupleDialogList temp=new CoupleDialogList(main.getCoppie(),false);
                temp.setVisible(true);
                
    }//GEN-LAST:event_showCouplesLoadedActionPerformed

    private void mobileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mobileActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mobileActionPerformed

    private void addCoupleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCoupleActionPerformed
        
        boolean tipo=true;
        String temp=mobile.getSelectedItem().toString();
        if(temp.equals("Fissa")) tipo=false;
        main.addCoppia(namePlayer1.getText(), namePlayer2.getText(), tipo); // TODO add your handling code here:
        int t=0;
        addCoupleDialog.dispose();
        namePlayer1.setText("");
        namePlayer2.setText("");
        idCouple.setText(String.valueOf(main.getCoppie().size()));
        addCoupleDialog.setVisible(true);
    }//GEN-LAST:event_addCoupleActionPerformed

    private void stopAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stopAddActionPerformed
        addCoupleDialog.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_stopAddActionPerformed

    private void idCouplePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_idCouplePropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_idCouplePropertyChange

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
             System.setProperty("apple.laf.useScreenMenuBar", "true");
                System.setProperty("com.apple.mrj.application.apple.menu.about.name", "Test");
           
            UIManager.setLookAndFeel(
            UIManager.getSystemLookAndFeelClassName());
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GuiMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GuiMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GuiMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GuiMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GuiMain().setVisible(true);
                
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem aboutMenuItem;
    private javax.swing.JButton addCoppieButtonLoaded;
    private javax.swing.JButton addCouple;
    private javax.swing.JDialog addCoupleDialog;
    private javax.swing.JMenuItem contentsMenuItem;
    private javax.swing.JMenuItem copyMenuItem;
    private javax.swing.JMenuItem cutMenuItem;
    private javax.swing.JMenuItem deleteMenuItem;
    private javax.swing.JMenu editMenu;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JLabel idCouple;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLayeredPane layers;
    private javax.swing.JDialog listCoppie;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JComboBox mobile;
    private javax.swing.JTextField namePlayer1;
    private javax.swing.JTextField namePlayer2;
    private javax.swing.JMenuItem openMenuItem;
    private javax.swing.JPanel panelNotStarted;
    private javax.swing.JMenuItem pasteMenuItem;
    private javax.swing.JMenuItem saveAsMenuItem;
    private javax.swing.JMenuItem saveMenuItem;
    private javax.swing.JButton showCouplesLoaded;
    private javax.swing.JButton stopAdd;
    // End of variables declaration//GEN-END:variables
}
